server:
  port: 8888
  ssl:
    key-store: "classpath:keystore.p12"
    key-store-password: atlas@paXs9o9
    key-store-type: PKCS12
    key-alias: atlas
  servlet:
    context-path: /atlas
  tomcat:
    threads:
      min-spare: 20
      max: 300

app:
  security:
    keycloak:
      client-id: mesh.atlas.web

keycloak:
  admin:
    server-url: https://keycloak.ww.local:8443
    realm: atlas
    # Service account client with realm-management: view-users, manage-users, query-clients roles
    client-id: atlas-admin
    client-secret: gu4WNKbw6ynknyQZvzNvb2cDQt1QKUdk
    # Application client whose Client Roles are managed in the admin UI
    app-client-id: mesh.atlas.web

spring:
  application:
    name: mesh.atlas
  main:
    web-application-type: servlet
    banner-mode: "off"
  ssl:
    bundle:
      pem:
        keycloak:
          truststore:
            certificate: classpath:certs/ca.crt
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.ww.local:8443/realms/atlas
          jwk-set-uri: https://keycloak.ww.local:8443/realms/atlas/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://postgresql.ww.local:5432/atlas
    username: atlas
    password: atlas
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false
    properties:
      "[org.hibernate.envers.default_schema]": aud
      hibernate:
        format_sql: true
        default_schema: atlas
        envers:
          audit_table_suffix: _aud
          revision_field_name: rev
          revision_type_field_name: revtype
          store_data_at_delete: true

  thymeleaf:
    check-template-location: false

  flyway:
    baseline-on-migrate: true
    enabled: true
    default-schema: atlas
    create-schemas: true
    placeholder-replacement: false

logging:
  appender: default
  file:
    path: ./logs/
  level:
    pl.com.ww.mesh.atlas: debug
    org:
      springframework.security: DEBUG
      springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      springframework.ws.client.MessageTracing.sent: TRACE
      springframework.ws.client.MessageTracing.received: TRACE
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace